// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnvO03eoHr1ELBn5xEXqlbjKp2GvRmyQA',
    appId: '1:135646484807:web:38e376eaf557911afa5462',
    messagingSenderId: '135646484807',
    projectId: 'telephyapp',
    authDomain: 'telephyapp.firebaseapp.com',
    storageBucket: 'telephyapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU42j_U5GDlpi24I3CM8BF50MABsyMAcs',
    appId: '1:135646484807:android:794b2d3f812af9bffa5462',
    messagingSenderId: '135646484807',
    projectId: 'telephyapp',
    storageBucket: 'telephyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhBP9S-NTAqnuRTzbqYTshvf2urG9kzZk',
    appId: '1:135646484807:ios:250743fbbcae1166fa5462',
    messagingSenderId: '135646484807',
    projectId: 'telephyapp',
    storageBucket: 'telephyapp.appspot.com',
    iosBundleId: 'com.example.telephy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhBP9S-NTAqnuRTzbqYTshvf2urG9kzZk',
    appId: '1:135646484807:ios:623259254df676f3fa5462',
    messagingSenderId: '135646484807',
    projectId: 'telephyapp',
    storageBucket: 'telephyapp.appspot.com',
    iosBundleId: 'com.example.telephy.RunnerTests',
  );
}
